name: Release gem to RubyGems.org

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without publishing to RubyGems"
        type: boolean
        default: false

jobs:
  release:
    uses: SOFware/reissue/.github/workflows/shared-ruby-gem-release.yml@main
    with:
      git_user_name: "SOFware"
      git_user_email: "github-actions[bot]@users.noreply.github.com"
      ruby_version: "3.4"
      dry_run: ${{ inputs.dry_run }}
